# Generated by Django 5.1.5 on 2025-02-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='projects', verbose_name='Image')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Web direction')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Edition date')),
            ],
            options={
                'verbose_name': 'projects',
                'verbose_name_plural': 'projects',
                'ordering': ['-created'],
            },
        ),
    ]
